name: Build binaries

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-binaries:
    name: Build binaries (${{ matrix.target }})
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: macos
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest
      - run: bun install
      - run: sudo apt install libdbus-1-dev pkg-config
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: bun run compile
      - name: Rename binaries to include platform
        run: bun -e "['cli', 'cli.exe'].forEach(name => { if (fs.existsSync('dist/'+name)) fs.renameSync('dist/'+name, 'dist/'+name+'-${{ matrix.target }}') })"
      - uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.target }}
          path: dist/cli-*